# Generated by Django 3.1.3 on 2020-11-25 01:31

from django.db import migrations, models
import django.utils.timezone
import marketech.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=225, unique=True)),
                ('apellido', models.CharField(db_column='apellido', max_length=225)),
                ('correo', models.CharField(db_column='correo', max_length=255, unique=True)),
                ('contrasena', models.CharField(db_column='contrasena', max_length=225)),
                ('telefono', models.IntegerField(db_column='telefono', unique=True)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('sexo', models.CharField(db_column='sexo', max_length=50)),
                ('imagen', models.CharField(db_column='imagen', max_length=225)),
                ('direccion', models.CharField(db_column='direccion', max_length=225)),
                ('creado_el', models.DateField(auto_now_add=True, db_column='creado_el')),
                ('actualizado_el', models.DateField(auto_now=True, db_column='actualizado_el')),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', marketech.models.ModificarUsuario()),
            ],
        ),
    ]
